version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build Lex Bundle
          command: npm run buildLex
  test:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dev-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM (Dev)
          command: npm install --dev
      - save_cache:
          key: dev-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build