version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:6.10
    steps:
      - checkout

      - run:
          name: Install NPM
          command: npm install

      - run:
          name: Build Lex Bundle
          command: npm run buildLex
  test:
    working_directory: ~/repo

    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run:
          name: Install NPM (Dev)
          command: npm install --dev
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master